name: Docker build and deploy Image

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build the Docker image
      run: docker build . --file server/Dockerfile --tag ghcr.io/${{ github.repository_owner }}/gnolove-server:cf23ce0
      
    - name: Push Docker image
      run: |
          docker push ghcr.io/${{ github.repository_owner }}/gnolove-server:cf23ce0
