name: Docker build and deploy Image V2

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Define image tag
      id: vars
      run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          
    - name: Build the Docker image
      run: | 
        docker build server --file server/Dockerfile \
        --tag ghcr.io/${{ github.repository_owner }}/gnolove-server:${{ steps.vars.outputs.tag }} \
        --tag ghcr.io/${{ github.repository_owner }}/gnolove-server:latest

      
    - name: Push Docker image
      run: |
          docker push ghcr.io/${{ github.repository_owner }}/gnolove-server:${{ steps.vars.outputs.tag }}
          docker push ghcr.io/${{ github.repository_owner }}/gnolove-server:latest

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
              cd /chemin/vers/ton/projet
              docker compose pull
              docker compose up -d
